- name: check the number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} greater than or equal to 10"
    when: number < 10

    